# BE CAREFUL MODIFYING THIS FILE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 2
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: gcr.io/gems-org/registry-dev:VERSION
        command: ["./registry"]
        args: ["--env=staging"]
        env:
        - name: REGISTRY_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: REGISTRY_DB_HOST
        - name: REGISTRY_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: REGISTRY_DB_PORT
        - name: REGISTRY_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: REGISTRY_DB_NAME
        - name: REGISTRY_DB_USER
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: REGISTRY_DB_USER
        - name: REGISTRY_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: REGISTRY_DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: JWT_SECRET
        ports:
        - containerPort: 8184
        resources: {}
      
---
apiVersion: batch/v1
kind: Job
metadata:
  name: registry-migration
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: registry-migration
    spec:
      containers:
      - name: registry-migration
        image: gcr.io/gems-org/registry-dev-migration:VERSION
        args: ["composeup"]
        env:
        - name: REGISTRY_DB_HOST
          value: "cloudsql-proxy"
        - name: REGISTRY_DB_PORT
          value: "3306"
        - name: REGISTRY_DB_NAME
          value: "registry_staging"
        - name: REGISTRY_DB_USER
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: REGISTRY_DB_USER
        - name: REGISTRY_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: registry-data
              key: REGISTRY_DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 4
---

apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
  - port: 80
    targetPort: 8184
  type: LoadBalancer
